name: my_homework_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.0.0
  get: ^4.7.2
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  syncfusion_flutter_calendar: ^30.1.42
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_sign_in: ^7.1.1
  provider: ^6.1.5
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/bg1.png
  - assets/logo.png
